Update workflows for Rust

diff --git a/.github/workflows/mingw.yml b/.github/workflows/mingw.yml
--- a/.github/workflows/mingw.yml
+++ b/.github/workflows/mingw.yml
@@ -3,8 +3,6 @@ on:
   push:
     branches:
       - '*'
-  schedule:
-    - cron: '45 1,8,15 * * *'
   workflow_dispatch:
 
 jobs:
@@ -35,17 +33,30 @@ jobs:
         timeout-minutes: 8
         uses: ruby/setup-ruby-pkgs@v1
         with:
-          ruby-version: mingw
-          mingw: clang
+          ruby-version: 3.2
+          mingw: clang-15 rust
 
-      - name: Install/Update Rust
-        uses: dtolnay/rust-toolchain@stable
-        with:
-          toolchain: stable-x86_64-pc-windows-gnu
-          components: rustfmt
+      - name: Configure bindgen
+        shell: bash
+        run: |
+          : Configure bindgen for msys2
 
-#      - name: install rust
-#        run: pacman -S --noconfirm --noprogressbar --needed mingw-w64-x86_64-rust
+          msys_root=""
+
+          if [ "$MSYSTEM" = "MINGW64" ]; then
+            msys_root="c:/msys64/mingw64"
+          elif [ "$MSYSTEM" = "UCRT64" ]; then
+            msys_root="c:/msys64/ucrt64"
+          else
+            echo "Unknown MSYSTEM: $MSYSTEM, cannot configure bindgen"
+            exit 1
+          fi
+
+          # We can't use llvm-16 just yet due to backwards compatibility issues, so we have to workaround for now
+          echo MSYS_ROOT="$msys_root" >> $GITHUB_ENV
+          echo LIBCLANG_PATH="$msys_root/opt/llvm-15/bin" >> $GITHUB_ENV
+
+          echo "::info::Set LIBCLANG_PATH to $LIBCLANG_PATH"
 
       - name: Cache - .downloaded-cache
         uses: actions/cache@v3
